# Generated by Django 6.0.3 on 2026-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_brand_category_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
