# Generated by Django 6.0.3 on 2026-03-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0003_alter_category_options_product_amazon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, help_text='A detailed paragraph about the product', null=True),
        ),
    ]
