# Generated by Django 6.0.3 on 2026-03-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0004_product_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amazon_link',
            new_name='gadget_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='about',
        ),
    ]
