# Generated by Django 6.0.3 on 2026-04-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_currency',
        ),
    ]
